/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated/logistics'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAuditOrderIdRouteImport } from './routes/_authenticated/audit/$orderId'
import { Route as AuthenticatedDisputesDisputeIdRouteImport } from './routes/_authenticated/disputes/$disputeId'
import { Route as AuthenticatedNegotiateSessionIdRouteImport } from './routes/_authenticated/negotiate/$sessionId'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedShipmentsTrackingIdRouteImport } from './routes/_authenticated/shipments/$trackingId'
import { Route as AuthenticatedOrdersOrderIdIndexRouteImport } from './routes/_authenticated/orders/$orderId/index'
import { Route as AuthenticatedOrdersOrderIdSettlementRouteImport } from './routes/_authenticated/orders/$orderId/settlement'
import { Route as ApiPublicWebhooksLogisticsRouteImport } from './routes/api/public/webhooks/logistics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditOrderIdRoute =
  AuthenticatedAuditOrderIdRouteImport.update({
    id: '/audit/$orderId',
    path: '/audit/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputesDisputeIdRoute =
  AuthenticatedDisputesDisputeIdRouteImport.update({
    id: '/disputes/$disputeId',
    path: '/disputes/$disputeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNegotiateSessionIdRoute =
  AuthenticatedNegotiateSessionIdRouteImport.update({
    id: '/negotiate/$sessionId',
    path: '/negotiate/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShipmentsTrackingIdRoute =
  AuthenticatedShipmentsTrackingIdRouteImport.update({
    id: '/shipments/$trackingId',
    path: '/shipments/$trackingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdIndexRoute =
  AuthenticatedOrdersOrderIdIndexRouteImport.update({
    id: '/orders/$orderId/',
    path: '/orders/$orderId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersOrderIdSettlementRoute =
  AuthenticatedOrdersOrderIdSettlementRouteImport.update({
    id: '/orders/$orderId/settlement',
    path: '/orders/$orderId/settlement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksLogisticsRoute =
  ApiPublicWebhooksLogisticsRouteImport.update({
    id: '/api/public/webhooks/logistics',
    path: '/api/public/webhooks/logistics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit/$orderId': typeof AuthenticatedAuditOrderIdRoute
  '/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/negotiate/$sessionId': typeof AuthenticatedNegotiateSessionIdRoute
  '/shipments/$trackingId': typeof AuthenticatedShipmentsTrackingIdRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/orders/$orderId/settlement': typeof AuthenticatedOrdersOrderIdSettlementRoute
  '/api/public/webhooks/logistics': typeof ApiPublicWebhooksLogisticsRoute
  '/orders/$orderId/': typeof AuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/audit/$orderId': typeof AuthenticatedAuditOrderIdRoute
  '/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/negotiate/$sessionId': typeof AuthenticatedNegotiateSessionIdRoute
  '/shipments/$trackingId': typeof AuthenticatedShipmentsTrackingIdRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/orders/$orderId/settlement': typeof AuthenticatedOrdersOrderIdSettlementRoute
  '/api/public/webhooks/logistics': typeof ApiPublicWebhooksLogisticsRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/audit/$orderId': typeof AuthenticatedAuditOrderIdRoute
  '/_authenticated/disputes/$disputeId': typeof AuthenticatedDisputesDisputeIdRoute
  '/_authenticated/negotiate/$sessionId': typeof AuthenticatedNegotiateSessionIdRoute
  '/_authenticated/shipments/$trackingId': typeof AuthenticatedShipmentsTrackingIdRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/orders/$orderId/settlement': typeof AuthenticatedOrdersOrderIdSettlementRoute
  '/api/public/webhooks/logistics': typeof ApiPublicWebhooksLogisticsRoute
  '/_authenticated/orders/$orderId/': typeof AuthenticatedOrdersOrderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/settings'
    | '/audit/$orderId'
    | '/disputes/$disputeId'
    | '/negotiate/$sessionId'
    | '/shipments/$trackingId'
    | '/orders/'
    | '/orders/$orderId/settlement'
    | '/api/public/webhooks/logistics'
    | '/orders/$orderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalog'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/settings'
    | '/audit/$orderId'
    | '/disputes/$disputeId'
    | '/negotiate/$sessionId'
    | '/shipments/$trackingId'
    | '/orders'
    | '/orders/$orderId/settlement'
    | '/api/public/webhooks/logistics'
    | '/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/catalog'
    | '/_authenticated/dashboard'
    | '/_authenticated/logistics'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/audit/$orderId'
    | '/_authenticated/disputes/$disputeId'
    | '/_authenticated/negotiate/$sessionId'
    | '/_authenticated/shipments/$trackingId'
    | '/_authenticated/orders/'
    | '/_authenticated/orders/$orderId/settlement'
    | '/api/public/webhooks/logistics'
    | '/_authenticated/orders/$orderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWebhooksLogisticsRoute: typeof ApiPublicWebhooksLogisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$orderId': {
      id: '/_authenticated/audit/$orderId'
      path: '/audit/$orderId'
      fullPath: '/audit/$orderId'
      preLoaderRoute: typeof AuthenticatedAuditOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes/$disputeId': {
      id: '/_authenticated/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof AuthenticatedDisputesDisputeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negotiate/$sessionId': {
      id: '/_authenticated/negotiate/$sessionId'
      path: '/negotiate/$sessionId'
      fullPath: '/negotiate/$sessionId'
      preLoaderRoute: typeof AuthenticatedNegotiateSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/$trackingId': {
      id: '/_authenticated/shipments/$trackingId'
      path: '/shipments/$trackingId'
      fullPath: '/shipments/$trackingId'
      preLoaderRoute: typeof AuthenticatedShipmentsTrackingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId/': {
      id: '/_authenticated/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId/'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/$orderId/settlement': {
      id: '/_authenticated/orders/$orderId/settlement'
      path: '/orders/$orderId/settlement'
      fullPath: '/orders/$orderId/settlement'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdSettlementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/logistics': {
      id: '/api/public/webhooks/logistics'
      path: '/api/public/webhooks/logistics'
      fullPath: '/api/public/webhooks/logistics'
      preLoaderRoute: typeof ApiPublicWebhooksLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAuditOrderIdRoute: typeof AuthenticatedAuditOrderIdRoute
  AuthenticatedDisputesDisputeIdRoute: typeof AuthenticatedDisputesDisputeIdRoute
  AuthenticatedNegotiateSessionIdRoute: typeof AuthenticatedNegotiateSessionIdRoute
  AuthenticatedShipmentsTrackingIdRoute: typeof AuthenticatedShipmentsTrackingIdRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedOrdersOrderIdSettlementRoute: typeof AuthenticatedOrdersOrderIdSettlementRoute
  AuthenticatedOrdersOrderIdIndexRoute: typeof AuthenticatedOrdersOrderIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAuditOrderIdRoute: AuthenticatedAuditOrderIdRoute,
  AuthenticatedDisputesDisputeIdRoute: AuthenticatedDisputesDisputeIdRoute,
  AuthenticatedNegotiateSessionIdRoute: AuthenticatedNegotiateSessionIdRoute,
  AuthenticatedShipmentsTrackingIdRoute: AuthenticatedShipmentsTrackingIdRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedOrdersOrderIdSettlementRoute:
    AuthenticatedOrdersOrderIdSettlementRoute,
  AuthenticatedOrdersOrderIdIndexRoute: AuthenticatedOrdersOrderIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWebhooksLogisticsRoute: ApiPublicWebhooksLogisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
